version: "3"

services:
  db:
    container_name: me-fdsz-database-dev
    image: mysql
    environment:
      MYSQL_USER: marci
      MYSQL_PASSWORD: userpass
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ME_FDSZ
    ports:
      - 33061:3306
#    expose:
#      - 33061
  backend:
    container_name: me-fdsz-backend-dev
    build:
      context: .
#      dockerfile: Dockerfile-dev
    links:
      - db:database
    ports:
      - 8080:8081
    depends_on:
      - db # start db before backend