version: "3"

services:
  db:
    image: mysql
    environment:
      MYSQL_USER: "marci"
      MYSQL_PASSWORD: "userpass"
      MYSQL_ROOT_PASSWORD: "rootpass"
    ports:
      - 33061:3306
    expose:
      - 33061
  backend:
    build: .
    links:
      - db:database
    ports:
      - 8080:8081
    depends_on:
      - db # start db before backend