FROM maven:3.6.2-jdk-11
LABEL maintainer="vmarci94@gmail.com"

#RUN apt-get update && apt-get install -y git
#RUN git clone https://github.com/Vmarci94/me-fdsz-be && cd me-fdsz-be && mvn clean package

# compiled binary path
ARG JAR_FILE_PATH=target/me-fdsz-1.0-SNAPSHOT.jar

# copy jar binary to container
COPY $JAR_FILE_PATH /

ENTRYPOINT ["java", "-Dspring.profiles.active=docker", "-jar", "me-fdsz-1.0-SNAPSHOT.jar"]